<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class DentalRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            //record
            'infirmary_id' => ['required', 'exists:clients,infirmary_id'],
            'dentist' => ['required', 'exists:users,id'],
            'or_no' => ['nullable', 'numeric', 'exists:payments_service,payment_id', Rule::unique('dental_records','or_no')->ignore($this->route('id'))],
            'is_out_patient' => ['required', 'boolean'],
            'status' => ['required', 'in:pending,done,released'],
            //results
            'examination_date' => ['required', 'date'],
            'age_last_birthday' => ['required', 'numeric'],
            //labio-buccal upper
            'lb_up_55' => ['nullable', 'boolean'],
            'lb_up_54' => ['nullable', 'boolean'],
            'lb_up_53' => ['nullable', 'boolean'],
            'lb_up_52' => ['nullable', 'boolean'],
            'lb_up_51' => ['nullable', 'boolean'],
            'lb_up_61' => ['nullable', 'boolean'],
            'lb_up_62' => ['nullable', 'boolean'],
            'lb_up_63' => ['nullable', 'boolean'],
            'lb_up_64' => ['nullable', 'boolean'],
            'lb_up_65' => ['nullable', 'boolean'],
            //labio-buccal upper operation
            'lb_op_up_55' => ['nullable', 'boolean'],
            'lb_op_up_54' => ['nullable', 'boolean'],
            'lb_op_up_53' => ['nullable', 'boolean'],
            'lb_op_up_52' => ['nullable', 'boolean'],
            'lb_op_up_51' => ['nullable', 'boolean'],
            'lb_op_up_61' => ['nullable', 'boolean'],
            'lb_op_up_62' => ['nullable', 'boolean'],
            'lb_op_up_63' => ['nullable', 'boolean'],
            'lb_op_up_64' => ['nullable', 'boolean'],
            'lb_op_up_65' => ['nullable', 'boolean'],
            //labio-buccal upper condition
            'lb_cond_up_55' => ['nullable', 'boolean'],
            'lb_cond_up_54' => ['nullable', 'boolean'],
            'lb_cond_up_53' => ['nullable', 'boolean'],
            'lb_cond_up_52' => ['nullable', 'boolean'],
            'lb_cond_up_51' => ['nullable', 'boolean'],
            'lb_cond_up_61' => ['nullable', 'boolean'],
            'lb_cond_up_62' => ['nullable', 'boolean'],
            'lb_cond_up_63' => ['nullable', 'boolean'],
            'lb_cond_up_64' => ['nullable', 'boolean'],
            'lb_cond_up_65' => ['nullable', 'boolean'],
            // labio-buccal upper
            'lb_up_18' => ['nullable', 'boolean'],
            'lb_up_17' => ['nullable', 'boolean'],
            'lb_up_16' => ['nullable', 'boolean'],
            'lb_up_15' => ['nullable', 'boolean'],
            'lb_up_14' => ['nullable', 'boolean'],
            'lb_up_13' => ['nullable', 'boolean'],
            'lb_up_12' => ['nullable', 'boolean'],
            'lb_up_11' => ['nullable', 'boolean'],
            'lb_up_21' => ['nullable', 'boolean'],
            'lb_up_22' => ['nullable', 'boolean'],
            'lb_up_23' => ['nullable', 'boolean'],
            'lb_up_24' => ['nullable', 'boolean'],
            'lb_up_25' => ['nullable', 'boolean'],
            'lb_up_26' => ['nullable', 'boolean'],
            'lb_up_27' => ['nullable', 'boolean'],
            'lb_up_28' => ['nullable', 'boolean'],
            //labio-buccal upper operation
            'lb_op_up_18' => ['nullable', 'boolean'],
            'lb_op_up_17' => ['nullable', 'boolean'],
            'lb_op_up_16' => ['nullable', 'boolean'],
            'lb_op_up_15' => ['nullable', 'boolean'],
            'lb_op_up_14' => ['nullable', 'boolean'],
            'lb_op_up_13' => ['nullable', 'boolean'],
            'lb_op_up_12' => ['nullable', 'boolean'],
            'lb_op_up_11' => ['nullable', 'boolean'],
            'lb_op_up_21' => ['nullable', 'boolean'],
            'lb_op_up_22' => ['nullable', 'boolean'],
            'lb_op_up_23' => ['nullable', 'boolean'],
            'lb_op_up_24' => ['nullable', 'boolean'],
            'lb_op_up_25' => ['nullable', 'boolean'],
            'lb_op_up_26' => ['nullable', 'boolean'],
            'lb_op_up_27' => ['nullable', 'boolean'],
            'lb_op_up_28' => ['nullable', 'boolean'],
            //labio-buccal upper condition
            'lb_cond_up_18'=>['nullable', 'boolean'],
            'lb_cond_up_17'=>['nullable', 'boolean'],
            'lb_cond_up_16'=>['nullable', 'boolean'],
            'lb_cond_up_15'=>['nullable', 'boolean'],
            'lb_cond_up_14'=>['nullable', 'boolean'],
            'lb_cond_up_13'=>['nullable', 'boolean'],
            'lb_cond_up_12'=>['nullable', 'boolean'],
            'lb_cond_up_11'=>['nullable', 'boolean'],
            'lb_cond_up_21'=>['nullable', 'boolean'],
            'lb_cond_up_22'=>['nullable', 'boolean'],
            'lb_cond_up_23'=>['nullable', 'boolean'],
            'lb_cond_up_24'=>['nullable', 'boolean'],
            'lb_cond_up_25'=>['nullable', 'boolean'],
            'lb_cond_up_26'=>['nullable', 'boolean'],
            'lb_cond_up_27'=>['nullable', 'boolean'],
            'lb_cond_up_28'=>['nullable', 'boolean'],
            //labio-buccal lower
            'lb_low_48' => ['nullable', 'boolean'],
            'lb_low_47' => ['nullable', 'boolean'],
            'lb_low_46' => ['nullable', 'boolean'],
            'lb_low_45' => ['nullable', 'boolean'],
            'lb_low_44' => ['nullable', 'boolean'],
            'lb_low_43' => ['nullable', 'boolean'],
            'lb_low_42' => ['nullable', 'boolean'],
            'lb_low_41' => ['nullable', 'boolean'],
            'lb_low_31' => ['nullable', 'boolean'],
            'lb_low_32' => ['nullable', 'boolean'],
            'lb_low_33' => ['nullable', 'boolean'],
            'lb_low_34' => ['nullable', 'boolean'],
            'lb_low_35' => ['nullable', 'boolean'],
            'lb_low_36' => ['nullable', 'boolean'],
            'lb_low_37' => ['nullable', 'boolean'],
            'lb_low_38' => ['nullable', 'boolean'],
            //labio-buccal lower operation
            'lb_op_low_48' => ['nullable', 'boolean'],
            'lb_op_low_47' => ['nullable', 'boolean'],
            'lb_op_low_46' => ['nullable', 'boolean'],
            'lb_op_low_45' => ['nullable', 'boolean'],
            'lb_op_low_44' => ['nullable', 'boolean'],
            'lb_op_low_43' => ['nullable', 'boolean'],
            'lb_op_low_42' => ['nullable', 'boolean'],
            'lb_op_low_41' => ['nullable', 'boolean'],
            'lb_op_low_31' => ['nullable', 'boolean'],
            'lb_op_low_32' => ['nullable', 'boolean'],
            'lb_op_low_33' => ['nullable', 'boolean'],
            'lb_op_low_34' => ['nullable', 'boolean'],
            'lb_op_low_35' => ['nullable', 'boolean'],
            'lb_op_low_36' => ['nullable', 'boolean'],
            'lb_op_low_37' => ['nullable', 'boolean'],
            'lb_op_low_38' => ['nullable', 'boolean'],
            //labio-buccal lower condition
            'lb_cond_low_48' => ['nullable', 'boolean'],
            'lb_cond_low_47' => ['nullable', 'boolean'],
            'lb_cond_low_46' => ['nullable', 'boolean'],
            'lb_cond_low_45' => ['nullable', 'boolean'],
            'lb_cond_low_44' => ['nullable', 'boolean'],
            'lb_cond_low_43' => ['nullable', 'boolean'],
            'lb_cond_low_42' => ['nullable', 'boolean'],
            'lb_cond_low_41' => ['nullable', 'boolean'],
            'lb_cond_low_31' => ['nullable', 'boolean'],
            'lb_cond_low_32' => ['nullable', 'boolean'],
            'lb_cond_low_33' => ['nullable', 'boolean'],
            'lb_cond_low_34' => ['nullable', 'boolean'],
            'lb_cond_low_35' => ['nullable', 'boolean'],
            'lb_cond_low_36' => ['nullable', 'boolean'],
            'lb_cond_low_37' => ['nullable', 'boolean'],
            'lb_cond_low_38' => ['nullable', 'boolean'],
            //labio-buccal lower
            'lb_low_85' => ['nullable', 'boolean'],
            'lb_low_84' => ['nullable', 'boolean'],
            'lb_low_83' => ['nullable', 'boolean'],
            'lb_low_82' => ['nullable', 'boolean'],
            'lb_low_81' => ['nullable', 'boolean'],
            'lb_low_71' => ['nullable', 'boolean'],
            'lb_low_72' => ['nullable', 'boolean'],
            'lb_low_73' => ['nullable', 'boolean'],
            'lb_low_74' => ['nullable', 'boolean'],
            'lb_low_75' => ['nullable', 'boolean'],
            //labio-buccal lower operation
            'lb_op_low_85' => ['nullable', 'boolean'],
            'lb_op_low_84' => ['nullable', 'boolean'],
            'lb_op_low_83' => ['nullable', 'boolean'],
            'lb_op_low_82' => ['nullable', 'boolean'],
            'lb_op_low_81' => ['nullable', 'boolean'],
            'lb_op_low_71' => ['nullable', 'boolean'],
            'lb_op_low_72' => ['nullable', 'boolean'],
            'lb_op_low_73' => ['nullable', 'boolean'],
            'lb_op_low_74' => ['nullable', 'boolean'],
            'lb_op_low_75' => ['nullable', 'boolean'],
            //labio-buccal lower condition
            'lb_cond_low_85' => ['nullable', 'boolean'],
            'lb_cond_low_84' => ['nullable', 'boolean'],
            'lb_cond_low_83' => ['nullable', 'boolean'],
            'lb_cond_low_82' => ['nullable', 'boolean'],
            'lb_cond_low_81' => ['nullable', 'boolean'],
            'lb_cond_low_71' => ['nullable', 'boolean'],
            'lb_cond_low_72' => ['nullable', 'boolean'],
            'lb_cond_low_73' => ['nullable', 'boolean'],
            'lb_cond_low_74' => ['nullable', 'boolean'],
            'lb_cond_low_75' => ['nullable', 'boolean'],

            'dental_caries' => ['required', 'boolean'],
            'gingivitis' => ['required', 'boolean'],
            'periodontal_pocket' => ['required', 'boolean'],
            'debris' => ['required', 'boolean'],
            'calculus'  => ['required', 'boolean'],
            'neoplasm'  => ['required', 'boolean'],
            'dento_facial' => ['required', 'boolean'],

            'cnt_prst_teeth' => ['required', 'numeric'],
            'cnt_indct_filing' => ['required', 'numeric'],
            'cnt_indct_extraction' => ['required', 'numeric'],
            'root_frgmt' => ['required', 'numeric'],
            'cnt_mssng_due_caries' => ['required', 'numeric'],
            'filled_restored' => ['required', 'numeric'],
            'cnt_df_dmf' => ['required', 'numeric'],
            'flouride_app' => ['required', 'numeric'],
        ];
    }

    public function messages()
    {
        return [
            //record
            'infirmary_id.required' => 'Required field',
            'infirmary_id.exists' => 'Patient ID does not exist',
            'dentist.required' => 'Required field',
            'dentist.exists' => 'Dentist does not exist',
            'or_no.numeric' => 'Invalid format',
            'or_no.exists' => 'OR no. does not exist',
            'or_no.unique' => 'OR no. is already used',
            'dental_result_id.required' => 'Required field',
            'dental_result_id.exists' => 'Dental result does not exist',
            'is_out_patient.required' => 'Required field',
            'is_out_patient.boolean' => 'Invalid format',
            'status.required' => 'Required field',
            'status.in' => 'Invalid format',
            //results
            'examination_date.required' => 'Required field',
            'examination_date.date' => 'Invalid date format',
            'age_last_birthday.numeric' => 'Invalid age format',
            'age_last_birthday.required' => 'Invalid age format',
// labio-buccal upper
            'lb_up_55.boolean' => 'Invalid format',
            'lb_up_54.boolean' => 'Invalid format',
            'lb_up_53.boolean' => 'Invalid format',
            'lb_up_52.boolean' => 'Invalid format',
            'lb_up_51.boolean' => 'Invalid format',
            'lb_up_61.boolean' => 'Invalid format',
            'lb_up_62.boolean' => 'Invalid format',
            'lb_up_63.boolean' => 'Invalid format',
            'lb_up_64.boolean' => 'Invalid format',
            'lb_up_65.boolean' => 'Invalid format',
// labio-buccal upper operation
            'lb_op_up_55.boolean' => 'Invalid format',
            'lb_op_up_54.boolean' => 'Invalid format',
            'lb_op_up_53.boolean' => 'Invalid format',
            'lb_op_up_52.boolean' => 'Invalid format',
            'lb_op_up_51.boolean' => 'Invalid format',
            'lb_op_up_61.boolean' => 'Invalid format',
            'lb_op_up_62.boolean' => 'Invalid format',
            'lb_op_up_63.boolean' => 'Invalid format',
            'lb_op_up_64.boolean' => 'Invalid format',
            'lb_op_up_65.boolean' => 'Invalid format',
// labio-buccal upper condition
            'lb_cond_up_55.boolean' => 'Invalid format',
            'lb_cond_up_54.boolean' => 'Invalid format',
            'lb_cond_up_53.boolean' => 'Invalid format',
            'lb_cond_up_52.boolean' => 'Invalid format',
            'lb_cond_up_51.boolean' => 'Invalid format',
            'lb_cond_up_61.boolean' => 'Invalid format',
            'lb_cond_up_62.boolean' => 'Invalid format',
            'lb_cond_up_63.boolean' => 'Invalid format',
            'lb_cond_up_64.boolean' => 'Invalid format',
            'lb_cond_up_65.boolean' => 'Invalid format',
// labio-buccal upper
            'lb_up_18.boolean' => 'Invalid format',
            'lb_up_17.boolean' => 'Invalid format',
            'lb_up_16.boolean' => 'Invalid format',
            'lb_up_15.boolean' => 'Invalid format',
            'lb_up_14.boolean' => 'Invalid format',
            'lb_up_13.boolean' => 'Invalid format',
            'lb_up_12.boolean' => 'Invalid format',
            'lb_up_11.boolean' => 'Invalid format',
            'lb_up_21.boolean' => 'Invalid format',
            'lb_up_22.boolean' => 'Invalid format',
            'lb_up_23.boolean' => 'Invalid format',
            'lb_up_24.boolean' => 'Invalid format',
            'lb_up_25.boolean' => 'Invalid format',
            'lb_up_26.boolean' => 'Invalid format',
            'lb_up_27.boolean' => 'Invalid format',
            'lb_up_28.boolean' => 'Invalid format',
// labio-buccal upper operation
            'lb_op_up_18.boolean' => 'Invalid format',
            'lb_op_up_17.boolean' => 'Invalid format',
            'lb_op_up_16.boolean' => 'Invalid format',
            'lb_op_up_15.boolean' => 'Invalid format',
            'lb_op_up_14.boolean' => 'Invalid format',
            'lb_op_up_13.boolean' => 'Invalid format',
            'lb_op_up_12.boolean' => 'Invalid format',
            'lb_op_up_11.boolean' => 'Invalid format',
            'lb_op_up_21.boolean' => 'Invalid format',
            'lb_op_up_22.boolean' => 'Invalid format',
            'lb_op_up_23.boolean' => 'Invalid format',
            'lb_op_up_24.boolean' => 'Invalid format',
            'lb_op_up_25.boolean' => 'Invalid format',
            'lb_op_up_26.boolean' => 'Invalid format',
            'lb_op_up_27.boolean' => 'Invalid format',
            'lb_op_up_28.boolean' => 'Invalid format',
// labio-buccal upper condition
            'lb_cond_up_18.boolean' => 'Invalid format',
            'lb_cond_up_17.boolean' => 'Invalid format',
            'lb_cond_up_16.boolean' => 'Invalid format',
            'lb_cond_up_15.boolean' => 'Invalid format',
            'lb_cond_up_14.boolean' => 'Invalid format',
            'lb_cond_up_13.boolean' => 'Invalid format',
            'lb_cond_up_12.boolean' => 'Invalid format',
            'lb_cond_up_11.boolean' => 'Invalid format',
            'lb_cond_up_21.boolean' => 'Invalid format',
            'lb_cond_up_22.boolean' => 'Invalid format',
            'lb_cond_up_23.boolean' => 'Invalid format',
            'lb_cond_up_24.boolean' => 'Invalid format',
            'lb_cond_up_25.boolean' => 'Invalid format',
            'lb_cond_up_26.boolean' => 'Invalid format',
            'lb_cond_up_27.boolean' => 'Invalid format',
            'lb_cond_up_28.boolean' => 'Invalid format',
// labio-buccal lower
            'lb_low_85.boolean' => 'Invalid format',
            'lb_low_84.boolean' => 'Invalid format',
            'lb_low_83.boolean' => 'Invalid format',
            'lb_low_82.boolean' => 'Invalid format',
            'lb_low_81.boolean' => 'Invalid format',
            'lb_low_71.boolean' => 'Invalid format',
            'lb_low_72.boolean' => 'Invalid format',
            'lb_low_73.boolean' => 'Invalid format',
            'lb_low_74.boolean' => 'Invalid format',
            'lb_low_75.boolean' => 'Invalid format',
            'lb_low_76.boolean' => 'Invalid format',
            'lb_low_77.boolean' => 'Invalid format',
            'lb_low_78.boolean' => 'Invalid format',
            'lb_low_48.boolean' => 'Invalid format',
            'lb_low_47.boolean' => 'Invalid format',
            'lb_low_46.boolean' => 'Invalid format',
            'lb_low_45.boolean' => 'Invalid format',
            'lb_low_44.boolean' => 'Invalid format',
            'lb_low_43.boolean' => 'Invalid format',
            'lb_low_42.boolean' => 'Invalid format',
            'lb_low_41.boolean' => 'Invalid format',
// labio-buccal lower operation
            'lb_op_low_85.boolean' => 'Invalid format',
            'lb_op_low_84.boolean' => 'Invalid format',
            'lb_op_low_83.boolean' => 'Invalid format',
            'lb_op_low_82.boolean' => 'Invalid format',
            'lb_op_low_81.boolean' => 'Invalid format',
            'lb_op_low_71.boolean' => 'Invalid format',
            'lb_op_low_72.boolean' => 'Invalid format',
            'lb_op_low_73.boolean' => 'Invalid format',
            'lb_op_low_74.boolean' => 'Invalid format',
            'lb_op_low_75.boolean' => 'Invalid format',
            'lb_op_low_76.boolean' => 'Invalid format',
            'lb_op_low_77.boolean' => 'Invalid format',
            'lb_op_low_78.boolean' => 'Invalid format',
            'lb_op_low_48.boolean' => 'Invalid format',
            'lb_op_low_47.boolean' => 'Invalid format',
            'lb_op_low_46.boolean' => 'Invalid format',
            'lb_op_low_45.boolean' => 'Invalid format',
            'lb_op_low_44.boolean' => 'Invalid format',
            'lb_op_low_43.boolean' => 'Invalid format',
            'lb_op_low_42.boolean' => 'Invalid format',
            'lb_op_low_41.boolean' => 'Invalid format',
// labio-buccal lower condition
            'lb_cond_low_85.boolean' => 'Invalid format',
            'lb_cond_low_84.boolean' => 'Invalid format',
            'lb_cond_low_83.boolean' => 'Invalid format',
            'lb_cond_low_82.boolean' => 'Invalid format',
            'lb_cond_low_81.boolean' => 'Invalid format',
            'lb_cond_low_71.boolean' => 'Invalid format',
            'lb_cond_low_72.boolean' => 'Invalid format',
            'lb_cond_low_73.boolean' => 'Invalid format',
            'lb_cond_low_74.boolean' => 'Invalid format',
            'lb_cond_low_75.boolean' => 'Invalid format',

            'dental_caries.required' => 'Required field',
            'gingivitis.required' => 'Required field',
            'periodontal_pocket.required' => 'Required field',
            'debris.required' => 'Required field',
            'calculus.required' => 'Required field',
            'neoplasm.required' => 'Required field',
            'dento_facial.required' => 'Required field',

            'dental_caries.boolean' => 'Invalid format',
            'gingivitis.boolean' => 'Invalid format',
            'periodontal_pocket.boolean' => 'Invalid format',
            'debris.boolean' => 'Invalid format',
            'calculus.boolean' => 'Invalid format',
            'neoplasm.boolean' => 'Invalid format',
            'dento_facial.boolean' => 'Invalid format',

            'cnt_prst_teeth.required' => 'Required field',
            'cnt_indct_filing.required' => 'Required field',
            'cnt_indct_extraction.required' => 'Required field',
            'root_frgmt.required' => 'Required field',
            'cnt_mssng_due_caries.required' => 'Required field',
            'filled_restored.required' => 'Required field',
            'cnt_df_dmf.required' => 'Required field',
            'flouride_app.required' => 'Required field',

            'cnt_prst_teeth.numeric' => 'Invalid format',
            'cnt_indct_filing.numeric' => 'Invalid format',
            'cnt_indct_extraction.numeric' => 'Invalid format',
            'root_frgmt.numeric' => 'Invalid format',
            'cnt_mssng_due_caries.numeric' => 'Invalid format',
            'filled_restored.numeric' => 'Invalid format',
            'cnt_df_dmf.numeric' => 'Invalid format',
            'flouride_app.numeric' => 'Invalid format',


        ];
    }
}
