<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dental extends Model
{
    use HasFactory;

    protected $table = 'dentals';

    protected $fillable = [
    'examination_date',
    'age_last_birthday',
    //labio-buccal upper
    'lb_up_55',
    'lb_up_54',
    'lb_up_53',
    'lb_up_52',
    'lb_up_51',
    'lb_up_61',
    'lb_up_62',
    'lb_up_63',
    'lb_up_64',
    'lb_up_65',
    //labio-buccal upper operation
    'lb_op_up_55',
    'lb_op_up_54',
    'lb_op_up_53',
    'lb_op_up_52',
    'lb_op_up_51',
    'lb_op_up_61',
    'lb_op_up_62',
    'lb_op_up_63',
    'lb_op_up_64',
    'lb_op_up_65',
    //labio-buccal upper condition
    'lb_cond_up_55',
    'lb_cond_up_54',
    'lb_cond_up_53',
    'lb_cond_up_52',
    'lb_cond_up_51',
    'lb_cond_up_61',
    'lb_cond_up_62',
    'lb_cond_up_63',
    'lb_cond_up_64',
    'lb_cond_up_65',
    // labio-buccal upper
    'lb_up_18',
    'lb_up_17',
    'lb_up_16',
    'lb_up_15',
    'lb_up_14',
    'lb_up_13',
    'lb_up_12',
    'lb_up_11',
    'lb_up_21',
    'lb_up_22',
    'lb_up_23',
    'lb_up_24',
    'lb_up_25',
    'lb_up_26',
    'lb_up_27',
    'lb_up_28',
    //labio-buccal upper operation
    'lb_op_up_18',
    'lb_op_up_17',
    'lb_op_up_16',
    'lb_op_up_15',
    'lb_op_up_14',
    'lb_op_up_13',
    'lb_op_up_12',
    'lb_op_up_11',
    'lb_op_up_21',
    'lb_op_up_22',
    'lb_op_up_23',
    'lb_op_up_24',
    'lb_op_up_25',
    'lb_op_up_26',
    'lb_op_up_27',
    'lb_op_up_28',
    //labio-buccal upper condition
    'lb_cond_up_18',
    'lb_cond_up_17',
    'lb_cond_up_16',
    'lb_cond_up_15',
    'lb_cond_up_14',
    'lb_cond_up_13',
    'lb_cond_up_12',
    'lb_cond_up_11',
    'lb_cond_up_21',
    'lb_cond_up_22',
    'lb_cond_up_23',
    'lb_cond_up_24',
    'lb_cond_up_25',
    'lb_cond_up_26',
    'lb_cond_up_27',
    'lb_cond_up_28',
    //labio-buccal lower
    'lb_low_48',
    'lb_low_47',
    'lb_low_46',
    'lb_low_45',
    'lb_low_44',
    'lb_low_43',
    'lb_low_42',
    'lb_low_41',
    'lb_low_31',
    'lb_low_32',
    'lb_low_33',
    'lb_low_34',
    'lb_low_35',
    'lb_low_36',
    'lb_low_37',
    'lb_low_38',
    //labio-buccal lower operation
    'lb_op_low_48',
    'lb_op_low_47',
    'lb_op_low_46',
    'lb_op_low_45',
    'lb_op_low_44',
    'lb_op_low_43',
    'lb_op_low_42',
    'lb_op_low_41',
    'lb_op_low_31',
    'lb_op_low_32',
    'lb_op_low_33',
    'lb_op_low_34',
    'lb_op_low_35',
    'lb_op_low_36',
    'lb_op_low_37',
    'lb_op_low_38',
    //labio-buccal lower condition
    'lb_cond_low_48',
    'lb_cond_low_47',
    'lb_cond_low_46',
    'lb_cond_low_45',
    'lb_cond_low_44',
    'lb_cond_low_43',
    'lb_cond_low_42',
    'lb_cond_low_41',
    'lb_cond_low_31',
    'lb_cond_low_32',
    'lb_cond_low_33',
    'lb_cond_low_34',
    'lb_cond_low_35',
    'lb_cond_low_36',
    'lb_cond_low_37',
    'lb_cond_low_38',
    //labio-buccal lower
    'lb_low_85',
    'lb_low_84',
    'lb_low_83',
    'lb_low_82',
    'lb_low_81',
    'lb_low_71',
    'lb_low_72',
    'lb_low_73',
    'lb_low_74',
    'lb_low_75',
    //labio-buccal lower operation
    'lb_op_low_85',
    'lb_op_low_84',
    'lb_op_low_83',
    'lb_op_low_82',
    'lb_op_low_81',
    'lb_op_low_71',
    'lb_op_low_72',
    'lb_op_low_73',
    'lb_op_low_74',
    'lb_op_low_75',
    //labio-buccal lower condition
    'lb_cond_low_85',
    'lb_cond_low_84',
    'lb_cond_low_83',
    'lb_cond_low_82',
    'lb_cond_low_81',
    'lb_cond_low_71',
    'lb_cond_low_72',
    'lb_cond_low_73',
    'lb_cond_low_74',
    'lb_cond_low_75',

    'dental_caries',
    'gingivitis',
    'periodontal_pocket',
    'debris',
    'calculus',
    'neoplasm',
    'dento_facial',

    'cnt_prst_teeth',
    'cnt_indct_filing',
    'cnt_indct_extraction',
    'root_frgmt',
    'cnt_mssng_due_caries',
    'filled_restored',
    'cnt_df_dmf',
    'flouride_app',
    ];

    public function dentalRecord()
    {
        return $this->hasOne(DentalRecord::class);
    }
}

